# Generated by Django 3.0.3 on 2020-02-21 06:25

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True,
                                              default=0,
                                              editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='storage',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='storage.Storage'),
        ),
    ]
