# Generated by Django 3.0.3 on 2020-02-22 07:11
# 设置按名称排序，并给物品增加价格，将位置和物品的名称设置成独一无二

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_mptt_rebuild'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
