# Generated by Django 3.0.3 on 2020-02-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_add_price_field_and_ordering_by_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={},
        ),
    ]
