# Generated by Django 3.0.3 on 2020-02-23 02:17

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20200223_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': '物品', 'verbose_name_plural': '物品'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': '位置', 'verbose_name_plural': '位置'},
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='item',
            name='number',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='item',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Storage', verbose_name='属于'),
        ),
        migrations.AlterField(
            model_name='item',
            name='update_date',
            field=models.DateTimeField(verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.Storage', verbose_name='属于'),
        ),
    ]
