version: '3'

services:
  web:
    image: he0119/smart-home
    container_name: smart-home
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.2
    container_name: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

networks:
  default:
    external:
      name: website
