version: '3'

services:
  web:
    image: he0119/smart-home:latest
    container_name: smart-home
    restart: always
    volumes:
      - ./static:/usr/src/app/static
    env_file:
      - ./.env
    depends_on:
      - db
      - mqtt
      - celery
      - redis
  celery:
    image: he0119/smart-home:latest
    command: celery -A home worker --beat -l info
    container_name: celery
    restart: always
    env_file:
      - ./.env
    depends_on:
      - redis
  db:
    build: ./docker/postgres
    container_name: postgres
    restart: always
    volumes:
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
  redis:
    image: redis:6.0.5-alpine
    container_name: redis
    restart: always
  mqtt:
    image: emqx/emqx:v4.1.1-alpine-amd64
    container_name: emqx
    restart: always
    env_file:
      - ./docker/emqx/configuration

networks:
  default:
    external:
      name: website
