version: '3'

services:
  web:
    image: he0119/smart-home:latest
    container_name: smart-home
    restart: always
    volumes:
      - ./static:/usr/src/app/static
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    build: ./docker/postgres
    container_name: postgres
    restart: always
    volumes:
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
  mqtt:
    image: eclipse-mosquitto:1.6.10
    container_name: mosquitto
    restart: always
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./docker/mosquitto/data:/mosquitto/data

networks:
  default:
    external:
      name: website
