version: '3'

services:
  django-web:
    build: .
    container_name: intelligent-home
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code

networks:
  default:
    external:
      name: website
