version: '3'
services:
  web:
    image: he0119/smart-home:latest
    container_name: smart-home
    restart: always
    user: 500:500
    volumes:
      - ./static:/usr/src/app/static
      - ./logs:/usr/src/app/logs
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  celery:
    image: he0119/smart-home:latest
    command: celery -A home worker --beat -l info
    container_name: celery
    restart: always
    user: 500:500
    volumes:
      - ./logs:/usr/src/app/logs
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgres:
    build: ./docker/postgres
    image: he0119/postgres:14
    container_name: postgres
    restart: always
    volumes:
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:6
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  default:
    external:
      name: website
