version: '3'

services:
  django-web:
    image: he0119/smart-home
    container_name: smart-home
    restart: always
    volumes:
      - ./static:/usr/src/app/static
      - ./db.sqlite3:/usr/src/app/db.sqlite3
    env_file:
      - ./.env

networks:
  default:
    external:
      name: website
