services:
  web:
    image: he0119/smart-home:latest
    container_name: smart-home
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
      - ./geoip:/app/geoip
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  celery:
    image: he0119/smart-home:latest
    command: uv run --no-dev celery -A home worker --beat -l info
    container_name: celery
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./geoip:/app/geoip
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgres:
    image: he0119/postgres
    build: ./docker/postgres
    container_name: postgres
    restart: always
    volumes:
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
