version: '3'

services:
  web:
    image: he0119/smart-home:latest
    container_name: smart-home
    restart: always
    volumes:
      - ./static:/usr/src/app/static
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    build: ./postgres
    container_name: postgres
    restart: always
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env

networks:
  default:
    external:
      name: website
