# Generated by Django 3.1.4 on 2020-12-29 17:34

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    """ 初始化默认 ACL """
    MQTTAcl = apps.get_model('iot', 'MQTTAcl')
    db_alias = schema_editor.connection.alias
    MQTTAcl.objects.using(db_alias).bulk_create([
        # 先禁止所有
        MQTTAcl(allow=0, username='$all', access=3, topic='device/+/set'),
        MQTTAcl(allow=0, username='$all', access=3, topic='device/+/status'),
        # 在允许设备订阅和发布自己用户名相关的
        MQTTAcl(allow=1, username='$all', access=1, topic='device/%u/set'),
        MQTTAcl(allow=1, username='$all', access=2, topic='device/%u/status'),
    ])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_add_index_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTAcl',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('allow', models.IntegerField(verbose_name='允许')),
                ('ipaddr',
                 models.CharField(blank=True,
                                  max_length=60,
                                  null=True,
                                  verbose_name='IP 地址')),
                ('username',
                 models.CharField(blank=True,
                                  max_length=100,
                                  null=True,
                                  verbose_name='用户名')),
                ('clientid',
                 models.CharField(blank=True,
                                  max_length=100,
                                  null=True,
                                  verbose_name='客户端 ID')),
                ('access', models.IntegerField(verbose_name='操作')),
                ('topic', models.CharField(max_length=100, verbose_name='主题')),
            ],
            options={
                'verbose_name': 'ACL 规则',
                'verbose_name_plural': 'ACL 规则',
                'db_table': 'mqtt_acl',
            },
        ),
        migrations.CreateModel(
            name='MQTTUser',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('password', models.CharField(max_length=100,
                                              verbose_name='密码')),
                ('salt',
                 models.CharField(blank=True,
                                  max_length=40,
                                  null=True,
                                  verbose_name='盐')),
                ('device',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='auth',
                     to='iot.device',
                     verbose_name='设备')),
            ],
            options={
                'verbose_name': 'MQTT 用户',
                'verbose_name_plural': 'MQTT 用户',
                'db_table': 'mqtt_user',
            },
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
