# Generated by Django 4.0.7 on 2022-09-29 02:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iot", "0007_add_autowatering_data_daily"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MQTTAcl",
        ),
    ]
