# Generated by Django 4.0.7 on 2022-09-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0008_delete_mqttacl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="password",
            new_name="token",
        ),
    ]
