# Generated by Django 5.1.1 on 2024-09-05 15:51

from django.db import migrations, models


def set_user_agent(apps, schema_editor):
    """将用户代理设置为空字符串"""
    Session = apps.get_model("users", "Session")
    for session in Session.objects.all():
        if session.user_agent is None:
            session.user_agent = ""
            session.save()


def reverse_set_user_agent(apps, schema_editor):
    """不需要做任何事情"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_session_user"),
    ]

    operations = [
        migrations.RunPython(set_user_agent, reverse_code=reverse_set_user_agent),
        migrations.AlterField(
            model_name="session",
            name="user_agent",
            field=models.CharField(blank=True, max_length=200, verbose_name="用户代理"),
        ),
    ]
