# Generated by Django 5.2.14 on 2026-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0005_rename_topic_is_pinned_is_closed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="comment",
            name="level",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name="层级"),
        ),
    ]
