# Generated by Django 4.0.7 on 2022-09-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_rename_topic_is_pinned_is_closed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="level",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="board.comment",
                verbose_name="属于",
            ),
        ),
    ]
