# Generated by Django 3.1.4 on 2020-12-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_item_consumables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='edited_at',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
    ]
