# Generated by Django 3.1.4 on 2021-02-01 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_do_not_allow_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemConsumables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='storage.item', verbose_name='耗材')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='storage.item', verbose_name='物品')),
            ],
            options={
                'verbose_name': '物品耗材',
                'verbose_name_plural': '物品耗材',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='consumables',
        ),
        migrations.AddField(
            model_name='item',
            name='consumables',
            field=models.ManyToManyField(blank=True, related_name='consumed_by', through='storage.ItemConsumables', to='storage.Item', verbose_name='耗材'),
        ),
        migrations.AddConstraint(
            model_name='itemconsumables',
            constraint=models.UniqueConstraint(fields=('item', 'consumable'), name='unique_item_consumable'),
        ),
    ]
