# Generated by Django 3.1.4 on 2021-02-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_do_not_allow_null'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE storage_item_consumables DROP CONSTRAINT storage_item_consumables_from_item_id_to_item_id_1fba0b1f_uniq',
                    reverse_sql='ALTER TABLE storage_item_consumables ADD CONSTRAINT storage_item_consumables_from_item_id_to_item_id_1fba0b1f_uniq UNIQUE (from_item_id, to_item_id)',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE storage_item_consumables RENAME TO storage_itemconsumables',
                    reverse_sql='ALTER TABLE storage_itemconsumables RENAME TO storage_item_consumables',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ItemConsumables',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='storage.item', verbose_name='耗材')),
                        ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='storage.item', verbose_name='物品')),
                    ],
                    options={
                        'verbose_name': '物品耗材',
                        'verbose_name_plural': '物品耗材',
                    },
                ),
                migrations.AlterField(
                    model_name='item',
                    name='consumables',
                    field=models.ManyToManyField(blank=True, related_name='consumed_by', through='storage.ItemConsumables', to='storage.Item', verbose_name='耗材'),
                ),
            ],
        ),
        migrations.RenameField(
            model_name='itemconsumables',
            old_name='to_item',
            new_name='consumable',
        ),
        migrations.RenameField(
            model_name='itemconsumables',
            old_name='from_item',
            new_name='item',
        ),
        migrations.AddField(
            model_name='itemconsumables',
            name='number',
            field=models.IntegerField(verbose_name='数量', default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='itemconsumables',
            constraint=models.UniqueConstraint(fields=('item', 'consumable'), name='unique_item_consumable'),
        ),
    ]
