# Generated by Django 3.1.7 on 2021-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0007_add_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.FloatField(blank=True, null=True, verbose_name="价格"),
        ),
    ]
