# Generated by Django 3.2 on 2021-04-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_remove_mptt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['name'], 'verbose_name': '位置', 'verbose_name_plural': '位置'},
        ),
    ]
