# Generated by Django 5.2.14 on 2026-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0009_remove_name_unique_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storage",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="storage",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="storage",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="storage",
            name="level",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name="层级"),
        ),
    ]
