name: Deploy

on:
  release:
    types: [released, edited]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.release) }}
        run: echo "$GITHUB_CONTEXT"
