name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setVersion.outputs.environment }}
      version: ${{ steps.setVersion.outputs.version }}
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:6.0.9-alpine
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: he0119/setup-python@main
        with:
          python-version: 3.9
      - name: Set build version
        id: setVersion
        run: |
          VERSION=$(poetry version -s)
          COMMIT_ID=$(git rev-parse --short HEAD)
          if [[ "${{github.event_name}}" == "release" && "${{github.event.action}}" == "published" ]]; then
            echo "::set-output name=environment::prod"
            echo "::set-output name=version::$VERSION"
          else
            echo "::set-output name=environment::dev"
            echo "::set-output name=version::$VERSION-git.$COMMIT_ID"
          fi
      - name: Install prerequisites
        run: poetry install
      - name: Run tests
        run: |
          poetry run coverage run manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
          poetry run coverage xml
        env:
          TESTING_SERVER: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set version name
        run: |
          sed -ri "s#release=\"version\"#release=\"$VERSION\"#g" home/settings/settings.py
        env:
          VERSION: ${{ needs.test.outputs.version }}
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: he0119/smart-home
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: docker
    environment:
      name: dev
      url: https://test.hehome.xyz
    if: github.event_name != 'pull_request'
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: TAG_NAME
          script: |
            cd websites
            sed -i "s#he0119/smart-home:.*#he0119/smart-home:master#g" docker-compose.yml
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker exec smart-home python manage.py migrate

  deploy_prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    needs: docker
    environment:
      name: prod
      url: https://smart.hehome.xyz
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: TAG_NAME
          script: |
            cd websites
            sed -i "s#he0119/smart-home:.*#he0119/smart-home:$TAG_NAME#g" docker-compose.yml
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker exec smart-home python manage.py migrate

  sentry_release:
    name: Sentry Release
    runs-on: ubuntu-latest
    needs: [test, docker]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: ${{ needs.test.outputs.environment }}
          version: ${{ needs.test.outputs.version }}
